/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.encrypt.view;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.security.SecureRandom;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class DecryptJInternalFrame extends javax.swing.JInternalFrame {

    private final static String AES = "AES";
    
    /**
     * Creates new form DecipherJInternalFrame
     */
    public DecryptJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decipherJPanel1 = new com.ouc.encrypt.view.DecryptJPanel();
        btnSearchKey = new javax.swing.JButton();
        txtdir = new javax.swing.JTextField();
        btnDecrypt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnSearchList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtdir1 = new javax.swing.JTextField();

        setClosable(true);

        decipherJPanel1.setPreferredSize(new java.awt.Dimension(832, 501));

        btnSearchKey.setText("选择密钥");
        btnSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKeyActionPerformed(evt);
            }
        });

        btnDecrypt.setText("确认解密");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        btnSearchList.setText("查询文件");
        btnSearchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchListActionPerformed(evt);
            }
        });

        jLabel1.setText("解密文件id：");

        txtId.setEnabled(false);

        btnSave.setText("保存路径");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout decipherJPanel1Layout = new javax.swing.GroupLayout(decipherJPanel1);
        decipherJPanel1.setLayout(decipherJPanel1Layout);
        decipherJPanel1Layout.setHorizontalGroup(
            decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnSearchList))
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(31, 31, 31)
                                .addComponent(txtdir1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(decipherJPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSearchKey)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(btnDecrypt)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        decipherJPanel1Layout.setVerticalGroup(
            decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decipherJPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnSearchList)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchKey)
                    .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecrypt))
                .addGap(18, 18, 18)
                .addGroup(decipherJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(txtdir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(decipherJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(decipherJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 选择解密密钥文件
    private void btnSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKeyActionPerformed
        JFileChooser openfile = new JFileChooser();//文件选择对话框
        FileFilter filter = new FileNameExtensionFilter("请选择密钥", "doc", "docx", "txt", "xlsx", "pdf");
        openfile.addChoosableFileFilter(filter);//添加过滤器
        openfile.setFileFilter(filter);
        int i = openfile.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            //jFileChooser.show(true);
            //输出绝对路径
            System.out.println(openfile.getSelectedFile().getAbsolutePath());
            txtdir.setText(openfile.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnSearchKeyActionPerformed
    
    // 显示id列表
    private void showOnTable(List<String> list) {
         // 1. 获取表格(tblProduct)模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblList.getModel();
        // 2. 清空表格信息
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        // 3.显示数据
        for (String s : list) {
            Vector vt = new Vector();
            vt.add(s);
            dtm.addRow(vt);
        }
    }
    
    // 查询获得id列表
    private void btnSearchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchListActionPerformed
        List<String> list = new ArrayList<String>();
        list.add("1");
        list.add("2");
        list.add("3");
        //list = fileList();
        //3 显示在表格
        showOnTable(list);
    }//GEN-LAST:event_btnSearchListActionPerformed

    // 鼠标选中列表某行，该行信息显示到文本框
    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        int row = this.tblList.getSelectedRow();
        // 根据row获取每列的值
        // 每行下标从0开始
        this.txtId.setText(this.tblList.getValueAt(row, 0)+"");
    }//GEN-LAST:event_tblListMouseClicked

    // 解密
    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser openfile = new JFileChooser();//文件选择对话框
        FileFilter filter = new FileNameExtensionFilter("请选择文件保存路径", "doc", "docx", "txt", "xlsx", "pdf");
        openfile.addChoosableFileFilter(filter);//添加过滤器
        openfile.setFileFilter(filter);
        int i = openfile.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            //jFileChooser.show(true);
            //输出绝对路径
            System.out.println(openfile.getSelectedFile().getAbsolutePath());
            txtdir.setText(openfile.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

     // 对密钥进行处理
    private static byte[] getRawKey(byte[] seed) throws Exception {
        KeyGenerator kgen = KeyGenerator.getInstance(AES);
        SecureRandom sr = null;
        sr = SecureRandom.getInstance("SHA1PRNG", "Crypto");
        return null;
    }

    /**
     * 解密
     */
    private static byte[] decrypt(String key, byte[] encrypted) throws Exception {
        byte[] raw = getRawKey(key.getBytes());
        SecretKeySpec skeySpec = new SecretKeySpec(raw, AES);
        Cipher cipher = Cipher.getInstance("CBC_PKCS5_PADDING");
        cipher.init(Cipher.DECRYPT_MODE, skeySpec, new IvParameterSpec(new byte[cipher.getBlockSize()]));
        byte[] decrypted = cipher.doFinal(encrypted);
        return decrypted;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchKey;
    private javax.swing.JButton btnSearchList;
    private com.ouc.encrypt.view.DecryptJPanel decipherJPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtdir1;
    // End of variables declaration//GEN-END:variables
}
